<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Direktori Organisasi NU Kecamatan
    |--------------------------------------------------------------------------
    |
    | Data direktori organisasi untuk halaman publik /organisasi.
    | - banom: kode di tabel `penguruses` untuk memuat struktur pengurus (null = belum ada data).
    | - terverifikasi: false berarti contoh data, ditandai jelas di halaman.
    |
    */

    'kategori' => [
        'semua' => 'Semua Organisasi',
        'pengurus' => 'Pengurus NU',
        'banom' => 'Badan Otonom',
        'lembaga' => 'Lembaga NU',
        'ranting' => 'Ranting NU',
    ],

    'organisasi' => [
        // ===== Pengurus NU =====
        [
            'slug' => 'mwcnu',
            'nama' => 'Majelis Wakil Cabang Nahdlatul Ulama',
            'singkatan' => 'MWCNU',
            'kategori' => 'pengurus',
            'banom' => 'mwcnu',
            'terverifikasi' => true,
            'deskripsi' => 'Induk organisasi NU tingkat kecamatan yang mengoordinasikan seluruh badan otonom, lembaga, dan ranting NU di wilayah kecamatan.',
            'sejarah' => 'MWCNU berdiri setelah PCNU Kabupaten Banyumas berkembang, sebagai majelis perwakilan yang menaungi puluhan Pengurus Ranting NU (PRNU) di desa-desa, termasuk Ranting NU.',
            'visi' => 'Terwujudnya kemandirian jam\'iyah dan jamaah Nahdlatul Ulama di tingkat kecamatan yang kokoh pada aqidah Ahlussunnah wal Jama\'ah.',
            'misi' => [
                'Mengoordinasikan seluruh badan otonom dan lembaga NU di tingkat kecamatan.',
                'Meningkatkan pelayanan pendidikan, kesehatan, ekonomi, dan maslahah bagi umat.',
                'Menjaga ukhuwah dan tradisi keagamaan Ahlussunnah wal Jama\'ah.',
            ],
            'program' => [
                'Koordinasi rapat kerja tahunan seluruh banom dan lembaga.',
                'Pembinaan kaderisasi kepemimpinan tingkat kecamatan.',
                'Pelayanan administrasi dan persuratan ranting NU.',
            ],
            'kontak' => 'Sekretariat MWCNU, Jl. Raya Cilongok, Banyumas.',
        ],
        [
            'slug' => 'prnu',
            'nama' => 'Pengurus Ranting NU',
            'singkatan' => 'PRNU ',
            'kategori' => 'pengurus',
            'banom' => 'ranting',
            'terverifikasi' => true,
            'deskripsi' => 'Pengurus Ranting Nahdlatul Ulama Desa a, bernaung di bawah MWCNU Kecamatan Cilongok dan PCNU Kabupaten Banyumas.',
            'sejarah' => 'Berdiri bersamaan dengan berkembangnya tradisi pesantren di Desa cilongok, PRNU a konsisten menggerakkan kegiatan keagamaan dan sosial kemasyarakatan.',
            'visi' => 'Melayani umat, memperkuat jamaah, dan membangun masyarakat bersama.',
            'misi' => [
                'Menyelenggarakan pengajian rutin dan majelis taklim.',
                'Mengelola infak dan sedekah untuk warga membutuhkan.',
                'Menjalin kerja sama dengan pemerintah desa dan pihak terkait.',
            ],
            'program' => [
                'Pengajian rutin dan majelis taklim pekanan.',
                'Pembinaan kaderisasi melalui badan otonom.',
                'Layanan sosial dan santunan warga dhuafa.',
            ],
            'kontak' => 'Gedung Sekretariat PRNU, Jl. Raya Cilongok No. 12, a.',
        ],

        // ===== Badan Otonom =====
        [
            'slug' => 'muslimat',
            'nama' => 'Muslimat Nahdlatul Ulama',
            'singkatan' => 'Muslimat NU',
            'kategori' => 'banom',
            'banom' => 'pac_muslimat',
            'terverifikasi' => true,
            'deskripsi' => 'Wadah perjuangan bagi perempuan lanjut usia dan tokoh wanita NU, menggerakkan majelis taklim serta kegiatan sosial kemasyarakatan.',
            'sejarah' => 'Muslimat NU tumbuh bersamaan dengan berdirinya NU, menjadi wadah utama perempuan NU dalam berdakwah dan melayani masyarakat.',
            'visi' => 'Terwujudnya perempuan NU yang berakhlak mulia, mandiri, dan bermanfaat bagi umat.',
            'misi' => [
                'Mengelola majelis taklim dan pembinaan keagamaan perempuan.',
                'Menggerakkan kegiatan sosial dan ekonomi kreatif keluarga.',
            ],
            'program' => [
                'Majelis taklim rutin ibu-ibu.',
                'Pelatihan keterampilan dan ekonomi kreatif.',
                'Santunan dan layanan sosial warga.',
            ],
            'kontak' => null,
        ],
        [
            'slug' => 'fatayat',
            'nama' => 'Fatayat Nahdlatul Ulama',
            'singkatan' => 'Fatayat NU',
            'kategori' => 'banom',
            'banom' => 'pac_fatayat',
            'terverifikasi' => true,
            'deskripsi' => 'Wadah bagi perempuan muda NU (maksimal 40 tahun) untuk pembinaan kepemimpinan, penguatan ekonomi keluarga, dan kesehatan masyarakat.',
            'sejarah' => 'Fatayat NU berdiri sebagai badan otonom perempuan muda yang bergerak di bidang keagamaan, sosial, dan pemberdayaan ekonomi keluarga.',
            'visi' => 'Menjadi wadah perempuan muda NU yang mandiri, berilmu, dan berkarakter.',
            'misi' => [
                'Membina kepemimpinan dan karakter perempuan muda NU.',
                'Menguatkan ekonomi keluarga dan kesehatan masyarakat.',
            ],
            'program' => [
                'Kajian dan pembinaan kader perempuan muda.',
                'Pelatihan ekonomi kreatif dan kewirausahaan.',
                'Kegiatan sosial dan kesehatan masyarakat.',
            ],
            'kontak' => null,
        ],
        [
            'slug' => 'gp-ansor',
            'nama' => 'Gerakan Pemuda Ansor',
            'singkatan' => 'GP Ansor',
            'kategori' => 'banom',
            'banom' => 'pac_ansor',
            'terverifikasi' => true,
            'deskripsi' => 'Organisasi kepemudaan NU yang bergerak di bidang keagamaan, sosial kemasyarakatan, dan pengawalan tradisi ulama.',
            'sejarah' => 'GP Ansor berdiri sebagai wadah pemuda NU yang setia menjaga tradisi dan ukhuwah, serta aktif dalam kegiatan sosial dan kemanusiaan.',
            'visi' => 'Terwujudnya pemuda NU yang berakhlak, mandiri, dan berjiwa sosial.',
            'misi' => [
                'Membina pemuda NU dalam keagamaan dan kepemimpinan.',
                'Mengawal kiai dan menjaga keamanan kegiatan keagamaan.',
            ],
            'program' => [
                'Pembinaan kader pemuda dan kepemimpinan.',
                'Kegiatan sosial, kemanusiaan, dan tanggap bencana.',
                'Pengawalan kegiatan keagamaan dan tradisi.',
            ],
            'kontak' => null,
        ],
        [
            'slug' => 'ipnu',
            'nama' => 'Ikatan Pelajar Nahdlatul Ulama',
            'singkatan' => 'IPNU',
            'kategori' => 'banom',
            'banom' => 'pac_ipnu',
            'terverifikasi' => true,
            'deskripsi' => 'Wadah bagi pelajar, santri, dan mahasiswa laki-laki NU (maksimal 27 tahun) untuk membina kepemimpinan dan karakter keislaman.',
            'sejarah' => 'IPNU berdiri sebagai badan otonom pelajar putra yang bergerak di bidang pendidikan, dakwah, dan kaderisasi kepemimpinan.',
            'visi' => 'Menjadi wadah pelajar NU yang berilmu, berakhlak, dan berjiwa kepemimpinan.',
            'misi' => [
                'Membina pelajar dan santri dalam ilmu dan akhlak.',
                'Mengembangkan kepemimpinan dan karakter keislaman.',
            ],
            'program' => [
                'Kajian pelajar dan pembinaan akhlak.',
                'Pelatihan kepemimpinan dan organisasi.',
                'Kegiatan dakwah dan sosial kemasyarakatan.',
            ],
            'kontak' => null,
        ],
        [
            'slug' => 'ippnu',
            'nama' => 'Ikatan Pelajar Putri Nahdlatul Ulama',
            'singkatan' => 'IPPNU',
            'kategori' => 'banom',
            'banom' => 'pac_ippnu',
            'terverifikasi' => true,
            'deskripsi' => 'Wadah bagi pelajar, santri, dan mahasiswi perempuan NU (maksimal 27 tahun) untuk pembinaan dan kaderisasi.',
            'sejarah' => 'IPPNU berdiri sebagai badan otonom pelajar putri yang bergerak di bidang pendidikan, dakwah, dan pembinaan kader perempuan.',
            'visi' => 'Menjadi wadah pelajar putri NU yang berilmu, berakhlak, dan mandiri.',
            'misi' => [
                'Membina pelajar dan santri putri dalam ilmu dan akhlak.',
                'Mengembangkan kepemimpinan perempuan muda NU.',
            ],
            'program' => [
                'Kajian pelajar putri dan pembinaan akhlak.',
                'Pelatihan kepemimpinan dan keterampilan.',
                'Kegiatan dakwah dan sosial kemasyarakatan.',
            ],
            'kontak' => null,
        ],
        [
            'slug' => 'pagar-nusa',
            'nama' => 'Pagar Nusa Nahdlatul Ulama',
            'singkatan' => 'Pagar Nusa',
            'kategori' => 'banom',
            'banom' => 'pac_pencak_silat',
            'terverifikasi' => false,
            'deskripsi' => 'Wadah bagi kader NU yang mendalami seni bela diri pencak silat, menjaga tradisi, dan membentuk karakter tangguh.',
            'sejarah' => 'Pagar Nusa berdiri sebagai wadah pencak silat NU yang menghubungkan olahraga bela diri dengan pembinaan akhlak dan ukhuwah.',
            'visi' => 'Terwujudnya kader NU yang tangguh, berakhlak, dan menjaga tradisi.',
            'misi' => [
                'Membina kader dalam seni bela diri dan karakter.',
                'Menjaga tradisi dan ukhuwah melalui olahraga.',
            ],
            'program' => [
                'Latihan rutin pencak silat.',
                'Pembinaan akhlak dan kepemimpinan kader.',
                'Pertemuan silaturahmi antar perguruan.',
            ],
            'kontak' => null,
        ],
        [
            'slug' => 'jatman',
            'nama' => 'Jam\'iyyah Ahli Thariqah al-Mu\'tabarah an-Nahdliyyah',
            'singkatan' => 'JATMAN',
            'kategori' => 'banom',
            'banom' => 'pac_jatman',
            'terverifikasi' => false,
            'deskripsi' => 'Wadah bagi pengamal ajaran thariqah mu\'tabarah yang berafiliasi dengan NU, menjaga tradisi zikir dan tawassul.',
            'sejarah' => 'JATMAN berdiri sebagai wadah ahli thariqah yang menjaga tradisi zikir, tawassul, dan ukhuwah dalam bingkai Ahlussunnah wal Jama\'ah.',
            'visi' => 'Menjaga tradisi thariqah mu\'tabarah dan ukhuwah jamaah.',
            'misi' => [
                'Membina pengamal thariqah dalam akhlak dan tradisi.',
                'Menjaga ukhuwah dan tradisi keagamaan.',
            ],
            'program' => [
                'Majelis zikir dan tawassul berkala.',
                'Pembinaan akhlak dan tradisi thariqah.',
                'Silaturahmi antar jamaah thariqah.',
            ],
            'kontak' => null,
        ],
        [
            'slug' => 'isnu',
            'nama' => 'Ikatan Sarjana Nahdlatul Ulama',
            'singkatan' => 'ISNU',
            'kategori' => 'banom',
            'banom' => 'pac_isnu',
            'terverifikasi' => false,
            'deskripsi' => 'Wadah bagi sarjana, intelektual, dan profesional NU yang berperan dalam pengembangan ilmu, pendidikan, dan pemberdayaan masyarakat.',
            'sejarah' => 'ISNU berdiri sebagai wadah sarjana NU yang mengabdikan ilmunya untuk kemajuan umat dan bangsa.',
            'visi' => 'Terwujudnya sarjana NU yang berilmu, berakhlak, dan berkontribusi bagi umat.',
            'misi' => [
                'Mengembangkan ilmu dan pendidikan berbasis nilai keislaman.',
                'Memberdayakan masyarakat melalui keahlian profesional.',
            ],
            'program' => [
                'Kajian ilmiah dan diskusi keislaman.',
                'Pemberdayaan masyarakat dan pelatihan keterampilan.',
                'Pendampingan pendidikan dan beasiswa.',
            ],
            'kontak' => null,
        ],
        [
            'slug' => 'pergunu',
            'nama' => 'Persatuan Guru Nahdlatul Ulama',
            'singkatan' => 'Pergunu',
            'kategori' => 'banom',
            'banom' => 'pac_pargu',
            'terverifikasi' => false,
            'deskripsi' => 'Wadah bagi guru dan pendidik berlatar belakang NU yang bergerak di bidang pendidikan, pembinaan akhlak, dan ukhuwah sesama pendidik.',
            'sejarah' => 'Pergunu berdiri sebagai wadah guru NU yang menjaga tradisi keilmuan dan ukhuwah di kalangan pendidik.',
            'visi' => 'Menjadi wadah guru NU yang berilmu, berakhlak, dan berdedikasi.',
            'misi' => [
                'Membina guru dalam keilmuan dan akhlak.',
                'Menjaga ukhuwah dan tradisi keilmuan.',
            ],
            'program' => [
                'Diskusi keilmuan dan pembinaan akhlak.',
                'Pelatihan keterampilan mengajar.',
                'Silaturahmi antar guru NU.',
            ],
            'kontak' => null,
        ],
        [
            'slug' => 'jqhnu',
            'nama' => 'Jam\'iyyatul Qurra wal Huffazh Nahdlatul Ulama',
            'singkatan' => 'JQHNU',
            'kategori' => 'banom',
            'banom' => 'pac_jqhnu',
            'terverifikasi' => false,
            'deskripsi' => 'Wadah bagi qari, qariah, dan penghafal Al-Qur\'an yang berperan dalam pembinaan seni baca dan hafalan Al-Qur\'an.',
            'sejarah' => 'JQHNU berdiri sebagai wadah qari dan penghafal Al-Qur\'an yang menjaga tradisi tilawah dan hafalan dalam bingkai NU.',
            'visi' => 'Menjaga tradisi tilawah dan hafalan Al-Qur\'an.',
            'misi' => [
                'Membina qari dan penghafal Al-Qur\'an.',
                'Mengembangkan seni baca dan hafalan Al-Qur\'an.',
            ],
            'program' => [
                'Majelis tilawah dan tahfidz berkala.',
                'Lomba dan pembinaan qari-qariah.',
                'Silaturahmi antar penghafal.',
            ],
            'kontak' => null,
        ],

        // ===== Lembaga NU =====
        [
            'slug' => 'lp-maarif',
            'nama' => 'Lembaga Pendidikan Ma\'arif NU',
            'singkatan' => 'LP Ma\'arif NU',
            'kategori' => 'lembaga',
            'banom' => null,
            'terverifikasi' => true,
            'deskripsi' => 'Lembaga pendidikan yang mengelola sekolah dan madrasah di bawah naungan NU, termasuk MTs Ma\'arif NU di wilayah Cilongok.',
            'sejarah' => 'LP Ma\'arif NU berdiri sebagai lembaga pendidikan yang mengelola puluhan sekolah dan madrasah NU secara mandiri, dengan semangat kebersamaan yang ditandai diresmikannya Joglo Ma\'arif sebagai pusat koordinasi pendidikan di Cilongok.',
            'visi' => 'Menghasilkan generasi yang berilmu, bertakwa, dan berkarakter.',
            'misi' => [
                'Mengelola sekolah dan madrasah berbasis nilai keislaman.',
                'Mengembangkan kurikulum yang memadukan ilmu umum dan agama.',
            ],
            'program' => [
                'Pengelolaan MTs Ma\'arif NU dan madrasah binaan.',
                'Pembinaan guru dan tenaga kependidikan.',
                'Kegiatan ekstrakurikuler dan pembinaan karakter.',
            ],
            'kontak' => null,
        ],
        [
            'slug' => 'lazisnu',
            'nama' => 'Lembaga Amil Zakat, Infaq, dan Sedekah NU',
            'singkatan' => 'LAZISNU',
            'kategori' => 'lembaga',
            'banom' => 'mwclazisnu',
            'terverifikasi' => true,
            'deskripsi' => 'Lembaga pengelola zakat, infaq, dan sedekah yang menyalurkan amanah donasi untuk kesehatan warga dhuafa, beasiswa santri, dan santunan yatim piatu.',
            'sejarah' => 'LAZISNU berdiri sebagai lembaga amil yang mengelola zakat, infaq, dan sedekah secara profesional dan transparan untuk kesejahteraan umat.',
            'visi' => 'Terwujudnya pengelolaan ZISWAF yang amanah, transparan, dan bermanfaat.',
            'misi' => [
                'Mengumpulkan dan mendistribusikan zakat, infaq, dan sedekah.',
                'Membiayai program kesehatan, pendidikan, dan santunan.',
            ],
            'program' => [
                'Pengumpulan zakat, infaq, dan sedekah.',
                'Santunan yatim piatu dan bantuan kesehatan dhuafa.',
                'Beasiswa santri madrasah.',
            ],
            'kontak' => null,
        ],
        [
            'slug' => 'rminu',
            'nama' => 'Rumah Sakit Islam Nahdlatul Ulama',
            'singkatan' => 'RMINU',
            'kategori' => 'lembaga',
            'banom' => null,
            'terverifikasi' => true,
            'deskripsi' => 'Lembaga kesehatan berbasis umat yang menyediakan layanan pengobatan murah dan mudah dijangkau bagi masyarakat luas.',
            'sejarah' => 'RMINU berdiri sebagai rumah sakit berbasis umat yang dirancang untuk melayani kesehatan masyarakat luas dengan nilai-nilai keislaman.',
            'visi' => 'Menjadi rumah sakit rujukan yang melayani dengan nilai keislaman.',
            'misi' => [
                'Menyediakan layanan kesehatan yang murah dan mudah dijangkau.',
                'Melayani dengan nilai keislaman dan kekeluargaan.',
            ],
            'program' => [
                'Layanan rawat jalan dan rawat inap.',
                'Program pelayanan kesehatan masyarakat.',
                'Pembinaan tenaga kesehatan berkarakter.',
            ],
            'kontak' => null,
        ],
        [
            'slug' => 'lbmnu',
            'nama' => 'Lembaga Baitul Maal Nahdlatul Ulama',
            'singkatan' => 'LBMNU',
            'kategori' => 'lembaga',
            'banom' => null,
            'terverifikasi' => false,
            'deskripsi' => 'Lembaga pengelola baitul maal yang mengumpulkan dan mendistribusikan dana sosial untuk kesejahteraan umat.',
            'sejarah' => 'LBMNU berdiri sebagai lembaga baitul maal yang mengelola dana sosial secara amanah untuk kesejahteraan umat.',
            'visi' => 'Terwujudnya pengelolaan dana sosial yang amanah dan bermanfaat.',
            'misi' => [
                'Mengumpulkan dan mendistribusikan dana sosial.',
                'Membiayai program kesejahteraan umat.',
            ],
            'program' => [
                'Pengumpulan dana sosial dan infaq.',
                'Penyaluran bantuan sosial.',
                'Pendampingan usaha kecil masyarakat.',
            ],
            'kontak' => null,
        ],
        [
            'slug' => 'ldnu',
            'nama' => 'Lembaga Dakwah Nahdlatul Ulama',
            'singkatan' => 'LDNU',
            'kategori' => 'lembaga',
            'banom' => null,
            'terverifikasi' => false,
            'deskripsi' => 'Lembaga dakwah yang mengkoordinasikan kegiatan dakwah, pembinaan majelis taklim, dan penyebaran Islam yang rahmatan lil alamin.',
            'sejarah' => 'LDNU berdiri sebagai lembaga dakwah yang menggerakkan kegiatan dakwah berkala dan pembinaan majelis taklim.',
            'visi' => 'Terwujudnya dakwah yang rahmatan lil alamin dan bermanfaat.',
            'misi' => [
                'Mengkoordinasikan kegiatan dakwah berkala.',
                'Membina majelis taklim dan muballigh.',
            ],
            'program' => [
                'Kegiatan dakwah berkala dan pembinaan muballigh.',
                'Pembinaan majelis taklim.',
                'Penerbitan dan penyebaran media dakwah.',
            ],
            'kontak' => null,
        ],
        [
            'slug' => 'ltmnu',
            'nama' => 'Lembaga Takmir Masjid Nahdlatul Ulama',
            'singkatan' => 'LTMNU',
            'kategori' => 'lembaga',
            'banom' => null,
            'terverifikasi' => false,
            'deskripsi' => 'Lembaga pengelola masjid dan mushala yang menjaga kebersihan, kenyamanan, dan kemakmuran tempat ibadah.',
            'sejarah' => 'LTMNU berdiri sebagai lembaga takmir yang mengelola masjid dan mushala agar tetap bersih, nyaman, dan makmur.',
            'visi' => 'Terwujudnya masjid dan mushala yang bersih, nyaman, dan makmur.',
            'misi' => [
                'Mengelola kebersihan dan kenyamanan masjid.',
                'Menggerakkan kemakmuran masjid melalui infak dan sedekah.',
            ],
            'program' => [
                'Pengelolaan kebersihan dan keamanan masjid.',
                'Penggerakan infak dan sedekah jamaah.',
                'Pembinaan takmir dan pengurus masjid.',
            ],
            'kontak' => null,
        ],
        [
            'slug' => 'lknu',
            'nama' => 'Lembaga Kesehatan Nahdlatul Ulama',
            'singkatan' => 'LKNU',
            'kategori' => 'lembaga',
            'banom' => null,
            'terverifikasi' => false,
            'deskripsi' => 'Lembaga kesehatan yang menyediakan layanan pengobatan murah dan mudah dijangkau bagi masyarakat, termasuk program pelayanan umat.',
            'sejarah' => 'LKNU berdiri sebagai lembaga kesehatan yang melayani masyarakat dengan layanan pengobatan murah dan mudah dijangkau.',
            'visi' => 'Terwujudnya layanan kesehatan yang murah dan mudah dijangkau.',
            'misi' => [
                'Menyediakan layanan pengobatan yang terjangkau.',
                'Melayani masyarakat dengan nilai keislaman.',
            ],
            'program' => [
                'Layanan pengobatan murah.',
                'Program pelayanan kesehatan masyarakat.',
                'Pembinaan tenaga kesehatan.',
            ],
            'kontak' => null,
        ],
        [
            'slug' => 'lwpnu',
            'nama' => 'Lembaga Wakaf Nahdlatul Ulama',
            'singkatan' => 'LWPNU',
            'kategori' => 'lembaga',
            'banom' => null,
            'terverifikasi' => false,
            'deskripsi' => 'Lembaga pengelola wakaf yang mengembangkan aset wakaf untuk kemaslahatan umat dan keberkahan jamaah.',
            'sejarah' => 'LWPNU berdiri sebagai lembaga wakaf yang mengelola dan mengembangkan aset wakaf secara produktif.',
            'visi' => 'Terwujudnya pengelolaan wakaf yang produktif dan bermanfaat.',
            'misi' => [
                'Mengelola dan mengembangkan aset wakaf.',
                'Menyalurkan hasil wakaf untuk kemaslahatan umat.',
            ],
            'program' => [
                'Pengelolaan aset wakaf tanah dan bangunan.',
                'Pengembangan wakaf produktif.',
                'Penyaluran hasil wakaf untuk pendidikan dan sosial.',
            ],
            'kontak' => null,
        ],
        [
            'slug' => 'ltnnu',
            'nama' => 'Lembaga Tanah Nahdlatul Ulama',
            'singkatan' => 'LTNNU',
            'kategori' => 'lembaga',
            'banom' => null,
            'terverifikasi' => false,
            'deskripsi' => 'Lembaga pengelola tanah dan aset organisasi NU yang menjaga keberlanjutan aset untuk kepentingan jamaah.',
            'sejarah' => 'LTNNU berdiri sebagai lembaga yang mengelola tanah dan aset organisasi NU secara amanah.',
            'visi' => 'Terwujudnya pengelolaan aset tanah yang amanah dan berkelanjutan.',
            'misi' => [
                'Mengelola tanah dan aset organisasi NU.',
                'Menjaga keberlanjutan aset untuk jamaah.',
            ],
            'program' => [
                'Pengelolaan sertifikat dan dokumen tanah.',
                'Pengembangan aset untuk kemaslahatan.',
                'Pendampingan legalitas aset organisasi.',
            ],
            'kontak' => null,
        ],
        [
            'slug' => 'lpbhnu',
            'nama' => 'Lembaga Pengkajian dan Bantuan Hukum NU',
            'singkatan' => 'LPBHNU',
            'kategori' => 'lembaga',
            'banom' => null,
            'terverifikasi' => false,
            'deskripsi' => 'Lembaga pengkajian dan bantuan hukum yang menyediakan konsultasi dan pendampingan hukum bagi masyarakat.',
            'sejarah' => 'LPBHNU berdiri sebagai lembaga yang menyediakan bantuan hukum dan pengkajian permasalahan hukum bagi masyarakat.',
            'visi' => 'Terwujudnya masyarakat yang terlindungi dan terlayani secara hukum.',
            'misi' => [
                'Menyediakan konsultasi dan bantuan hukum.',
                'Mengkaji permasalahan hukum masyarakat.',
            ],
            'program' => [
                'Konsultasi hukum gratis.',
                'Pendampingan perkara masyarakat.',
                'Sosialisasi hukum dan peraturan.',
            ],
            'kontak' => null,
        ],
        [
            'slug' => 'lesbumi',
            'nama' => 'Lembaga Sosial dan Bumi NU',
            'singkatan' => 'LESBUMI',
            'kategori' => 'lembaga',
            'banom' => null,
            'terverifikasi' => false,
            'deskripsi' => 'Lembaga sosial yang menggerakkan kegiatan kemanusiaan, tanggap bencana, dan pemberdayaan masyarakat.',
            'sejarah' => 'LESBUMI berdiri sebagai lembaga sosial yang aktif dalam kegiatan kemanusiaan dan tanggap bencana.',
            'visi' => 'Terwujudnya masyarakat yang tangguh dan saling membantu.',
            'misi' => [
                'Menggerakkan kegiatan kemanusiaan dan sosial.',
                'Menjadi tanggap bencana dan krisis.',
            ],
            'program' => [
                'Posko tanggap bencana.',
                'Santunan dan bantuan sosial.',
                'Pemberdayaan masyarakat rentan.',
            ],
            'kontak' => null,
        ],
        [
            'slug' => 'lakpesdam',
            'nama' => 'Lembaga Kaderisasi dan Pemberdayaan Masyarakat NU',
            'singkatan' => 'LAKPESDAM NU',
            'kategori' => 'lembaga',
            'banom' => null,
            'terverifikasi' => false,
            'deskripsi' => 'Lembaga kaderisasi dan pemberdayaan masyarakat yang membina kader NU dan menggerakkan program pemberdayaan.',
            'sejarah' => 'LAKPESDAM NU berdiri sebagai lembaga kaderisasi yang membina kader NU dan memberdayakan masyarakat.',
            'visi' => 'Terwujudnya kader NU yang berkualitas dan masyarakat yang mandiri.',
            'misi' => [
                'Membina kader NU melalui pendidikan dan pelatihan.',
                'Menggerakkan program pemberdayaan masyarakat.',
            ],
            'program' => [
                'Pendidikan dan pelatihan kader.',
                'Program pemberdayaan ekonomi masyarakat.',
                'Pendampingan organisasi kemasyarakatan.',
            ],
            'kontak' => null,
        ],
        [
            'slug' => 'lpbi',
            'nama' => 'Lembaga Penerbitan dan Buku NU',
            'singkatan' => 'LPBI NU',
            'kategori' => 'lembaga',
            'banom' => null,
            'terverifikasi' => false,
            'deskripsi' => 'Lembaga penerbitan dan buku yang mengelola penerbitan, perpustakaan, dan literasi baca bagi jamaah.',
            'sejarah' => 'LPBI NU berdiri sebagai lembaga penerbitan yang mengelola buku, majalah, dan media baca berbasis nilai keislaman.',
            'visi' => 'Terwujudnya masyarakat yang gemar membaca dan berilmu.',
            'misi' => [
                'Mengelola penerbitan buku dan majalah.',
                'Mengembangkan perpustakaan dan literasi baca.',
            ],
            'program' => [
                'Penerbitan buku dan majalah berkala.',
                'Pengelolaan perpustakaan keliling.',
                'Pelatihan menulis dan literasi digital.',
            ],
            'kontak' => null,
        ],
        [
            'slug' => 'lptnu',
            'nama' => 'Lembaga Penerangan dan Tabligh NU',
            'singkatan' => 'LPTNU',
            'kategori' => 'lembaga',
            'banom' => null,
            'terverifikasi' => false,
            'deskripsi' => 'Lembaga penerangan dan tabligh yang mengkoordinasikan dakwah, media, dan komunikasi organisasi NU.',
            'sejarah' => 'LPTNU berdiri sebagai lembaga penerangan yang mengelola media, komunikasi, dan kegiatan tabligh.',
            'visi' => 'Terwujudnya dakwah yang efektif melalui media dan komunikasi.',
            'misi' => [
                'Mengkoordinasikan kegiatan tabligh dan dakwah.',
                'Mengelola media dan komunikasi organisasi.',
            ],
            'program' => [
                'Kegiatan tabligh dan dakwah berkala.',
                'Pengelolaan media cetak dan digital.',
                'Pelatihan muballigh dan media.',
            ],
            'kontak' => null,
        ],

        // ===== Ranting NU (contoh data per desa) =====
        [
            'slug' => 'prnu',
            'nama' => 'PRNU Desa ',
            'singkatan' => 'PRNU',
            'kategori' => 'ranting',
            'banom' => 'ranting',
            'terverifikasi' => true,
            'deskripsi' => 'Pengurus Ranting NU  bernaung di bawah MWCNU Kecamatan Cilongok dan PCNU Kabupaten Banyumas.',
            'sejarah' => 'Berdiri bersamaan dengan berkembangnya tradisi pesantren di Desa, konsisten menggerakkan kegiatan keagamaan dan sosial kemasyarakatan.',
            'visi' => 'Melayani umat, memperkuat jamaah, dan membangun masyarakat bersama.',
            'misi' => [
                'Menyelenggarakan pengajian rutin dan majelis taklim.',
                'Mengelola infak dan sedekah untuk warga membutuhkan.',
            ],
            'program' => [
                'Pengajian rutin dan majelis taklim pekanan.',
                'Pembinaan kaderisasi melalui badan otonom.',
                'Layanan sosial dan santunan warga dhuafa.',
            ],
            'kontak' => 'Gedung Sekretariat PRNU, Jl. Raya Cilongok No. 12,.',
        ],
        [
            'slug' => 'prnu-contoh-1',
            'nama' => 'PRNU Desa Contoh Satu',
            'singkatan' => 'PRNU Contoh 1',
            'kategori' => 'ranting',
            'banom' => null,
            'terverifikasi' => false,
            'deskripsi' => 'Contoh data ranting NU di desa lain dalam lingkunup kecamatan. Data ini belum terverifikasi keberadaannya.',
            'sejarah' => 'Contoh data untuk mengilustrasikan struktur ranting NU di desa lain.',
            'visi' => 'Melayani umat dan memperkuat jamaah di tingkat desa.',
            'misi' => [
                'Menyelenggarakan kegiatan keagamaan tingkat desa.',
                'Mengelola infak dan sedekah untuk warga.',
            ],
            'program' => [
                'Pengajian rutin tingkat desa.',
                'Kegiatan sosial dan santunan.',
            ],
            'kontak' => null,
        ],
        [
            'slug' => 'prnu-contoh-2',
            'nama' => 'PRNU Desa Contoh Dua',
            'singkatan' => 'PRNU Contoh 2',
            'kategori' => 'ranting',
            'banom' => null,
            'terverifikasi' => false,
            'deskripsi' => 'Contoh data ranting NU di desa lain dalam lingkunup kecamatan. Data ini belum terverifikasi keberadaannya.',
            'sejarah' => 'Contoh data untuk mengilustrasikan struktur ranting NU di desa lain.',
            'visi' => 'Melayani umat dan memperkuat jamaah di tingkat desa.',
            'misi' => [
                'Menyelenggarakan kegiatan keagamaan tingkat desa.',
                'Mengelola infak dan sedekah untuk warga.',
            ],
            'program' => [
                'Pengajian rutin tingkat desa.',
                'Kegiatan sosial dan santunan.',
            ],
            'kontak' => null,
        ],
    ],
];
